apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: miniexchange
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: miniexchange-api
        metrics_path: /metrics
        static_configs:
          - targets:
              - api:8080

      - job_name: miniexchange-consumer
        metrics_path: /metrics
        static_configs:
          - targets:
              - consumer:5001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: miniexchange
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v3.5.0
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml

      volumes:
        - name: config
          configMap:
            name: prometheus-config

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: miniexchange
spec:
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090
  type: NodePort