FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY NuGet.Docker.Config .

COPY ["src/MiniExchange.KafkaConsumer/MiniExchange.KafkaConsumer.csproj", "src/MiniExchange.KafkaConsumer/"]
COPY ["src/MiniExchange.Contracts/MiniExchange.Contracts.csproj", "src/MiniExchange.Contracts/"]

RUN dotnet restore \
    "src/MiniExchange.KafkaConsumer/MiniExchange.KafkaConsumer.csproj" \
    --configfile NuGet.Docker.Config

COPY src/ src/

RUN dotnet publish \
    "src/MiniExchange.KafkaConsumer/MiniExchange.KafkaConsumer.csproj" \
    -c Release \
    -o /app/publish \
    --no-restore

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 5000
EXPOSE 5001

ENTRYPOINT ["dotnet", "MiniExchange.KafkaConsumer.dll"]