apiVersion: v1
kind: Secret
metadata:
  name: miniexchange-postgres-secret
  namespace: miniexchange
type: Opaque
stringData:
  POSTGRES_USER: miniexchange
  POSTGRES_PASSWORD: miniexchange
  POSTGRES_DB: miniexchange